name: Test
on:
  - push
  - pull_request
jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependency packages
        run: |
          apt update
          apt install -y -V ca-certificates lsb-release wget
          wget \
            https://apache.jfrog.io/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
          apt install -y -V ./apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
          apt update
          apt install -y -V libarrow-dev
      - name: Install dependency gems
        run: |
          bundle install
      - name: Run tests
        run: |
          rake groonga:test
